### PR TITLE
chore: upgrade to cdk v2

### PR DESCRIPTION
**Pull request by corymhall**
Updating cdk to v2.

This PR also updates the tests to use assertions, but does keep the
snapshot test in order to include the snapshot diff in the PR.

re https://github.com/aws-samples/aws-cdk-intro-workshop/issues/308

BREAKING CHANGE: updates the dependency on aws-cdk to ^2.0.0-rc.28

### CODE REVIEW

**Review by njlynch — COMMENTED** [review]
Looks good to me. I still wonder if we should adopt "0.2.x" versioning instead of jumping straight to 4.x, just to denote this is still an alpha-level package. That being said, I don't feel super-strongly about it. Maybe get one more opinion (either way) before committing. :)

**Comment by corymhall** [comment]
> Looks good to me. I still wonder if we should adopt "0.2.x" versioning instead of jumping straight to 4.x, just to denote this is still an alpha-level package. That being said, I don't feel super-strongly about it. Maybe get one more opinion (either way) before committing. :)

@njlynch I removed the reference to major version 4 so it should now release as `v0.2.0`

**Review by eladb — APPROVED** [review]
Looks awesome!

@corymhall how was the migration experience? Did you follow any migration guide? (@njlynch do we have a v1 to v2 migration guide?)

**Comment by njlynch** [comment]
@eladb  - https://docs.aws.amazon.com/cdk/latest/guide/work-with-cdk-v2.html

**Pull request merged**
